### ISSUE TITLE
SUGGESTION: Commit Message

### ISSUE THREAD

**Issue by azanbinzahid** [froheel/Classroom#8]
Please try to incorporate [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) messages for better readability.

**Comment by froheel** [comment]
Thank you pointing this out and also sharing this useful link. I read the documentation and force pushing older commits is discouraged by GitHub. If you have experience related to updating already pushed commits then I would love to take your guidance on it. However, I'll definitely keep this convention in mind, when I commit next time. I appreciate you taking the time out to share this with me.

**Comment by azanbinzahid** [comment]
I guess there is no need to change prev commits or history. You can start using it in upcoming projects.
